# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
loader_version_range=[1,)

## Mod Properties

mod_id=woodencog
mod_name=WoodenCog
mod_license=MIT
mod_group_id=net.chauvedev.woodencog

mod_version = 1.2.17
neo_version=21.1.229
min_neo_version=21.1.0
forgegradle_version = 6.0.6
mixingradle_version = 0.7-SNAPSHOT
librarian_version = 1.+
shadow_version = 7.1.0
cursegradle_version = 1.4.0
parchment_version = 2023.06.26

mixin_version = 0.8.5
mixin_extras_version = 0.4.1

create_version = 6.0.10-281
ponder_version = 1.0.82
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67
patchouli_version = 93-NEOFORGE
jei_version = 19.27.0.340